language: cpp
sudo: required
dist: trusty
cache: apt

notifications:
  slack: ezlanguage:Lx6iO5M1QzE01l4om91A36fo

os:
  - linux
  
addons:
  apt:
    sources:
      # gcc/g++ repository
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

install:
# g++ install
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - alias g++="g++-5"

after_success:
# Launch tests
#  - ./bin/EZ_language_compiler

script:
  - make --file makefile -j2

