language: cpp
sudo: required
dist: trusty
cache: apt

notifications:
  slack: ezlanguage:Lx6iO5M1QzE01l4om91A36fo

os:
  - linux
  
addons:
  apt:
    sources:
      # gcc/g++ repository
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

before_install:
  - sudo apt-get update -qy
  - sudo apt-get install g++-5


install:
# g++ install
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-4.9"; fi
  - alias g++="g++-5"
  - g++ --version
  - echo -e "================="
  - $CXX --version

after_success:
# Launch tests
#  - ./bin/EZ_language_compiler

script:
  - make --file makefile -j2

